### ISSUE TITLE
No .datepicker method on elem

### ISSUE THREAD

**Issue by zygm0nt** [jducoeur/bootstrap-datepicker-scalajs#1]
Hi

I'm trying to use the following snippet from `README.md` but this doesn't seem to compile:

```
val elem = input().render
$(elem).datepicker(opts)

$(elem).on("changeDate", { rawEvt:JQueryEventObject =>
  save()
})
```

I don't have a `datepicker` method on my element. Is there something I'm missing here?

**Comment by jducoeur** [comment]
Hmm.  You need:

```
import org.querki.facades.bootstrap.datepicker._
```

Among other things, that adds the implicits that make this all work...

**Comment by zygm0nt** [comment]
Thanks, that worked.
